modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "mechanica"
version = "${version}"
displayName = "Mechanica"
authors = ["illuc"]
description = '''
A Clockwork addon.
'''
logoFile = "icon.png"

[[dependencies.mechanica]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mechanica]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mechanica]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mechanica]]
modId = "create"
mandatory = true
versionRange = "${create_version}"
ordering = "NONE"
side = "BOTH"
